// Hardware: what this machine can actually measure.
//
// The view states the browser's limits instead of asking for permissions on load: a
// capability is probed, reported with the reason it is limited or unsupported, and the
// operating system is only asked for access when the operator presses a button.

import {
  Activity, Bluetooth, CheckCircle2, Cpu, MapPin, Mic, Plus, Radio, RefreshCw, ScanLine,
  Shield, ShieldCheck, Smartphone, Wifi,
} from 'lucide-react';

import { BridgeDownload } from '../components/bridge-download';
import { MetricCard } from '../components/console';
import { PhoneRelay } from '../components/phone-relay';
import { useConsoleData } from '../lib/console-data';
import type { HardwareCapability, HardwareStatus } from '../lib/types';

function CapabilityIcon({ id }: { id: string }) {
  if (id === 'bluetooth') return <Bluetooth aria-hidden="true" />;
  if (id === 'wifi') return <Wifi aria-hidden="true" />;
  if (id === 'camera-mic') return <Mic aria-hidden="true" />;
  if (id === 'location') return <MapPin aria-hidden="true" />;
  if (id === 'motion') return <Activity aria-hidden="true" />;
  if (id === 'battery') return <Smartphone aria-hidden="true" />;
  return <Cpu aria-hidden="true" />;
}

export function Hardware() {
  const { hardware: capabilities, hardwareScan, hardwareRefreshing: refreshing, refreshHardware: onRefresh, requestHardware: onRequest, isMobile, apiStatus } = useConsoleData();
  const visibleCapabilities = isMobile ? capabilities.filter(capability => ['bluetooth', 'wifi'].includes(capability.id)) : capabilities;
  const connected = visibleCapabilities.filter(capability => capability.status === 'connected' || capability.status === 'ready').length;
  const supported = visibleCapabilities.filter(capability => capability.status !== 'unsupported').length;
  const statusLabel: Record<HardwareStatus, string> = { ready: 'ready', permission: 'permission needed', connected: 'connected', limited: 'limited', unsupported: 'not exposed' };
  return <><div className={`page-heading ${isMobile ? 'mobile-scan-heading' : ''}`}><div><div className="page-kicker">{isMobile ? 'Phone radio access' : 'Computer hardware bridge'}</div><h1>{isMobile ? 'Scan with your phone.' : 'Scan with your computer.'}</h1><p>{isMobile ? 'This device has hardware a page can measure with: where it is, whether it is moving, and — where this browser grants it — the Bluetooth advertisers it can hear. Nearby WiFi access points are only visible to a program running beside the adapter, never to a page. Start the relay below and walk a few metres to place what you hear.' : 'Scan from this device with no install, or download the local BackSpyne bridge on this computer to read WiFi access points and BLE advertisements through OS-approved adapters. Both paths report through the same account.'}</p></div><button className="btn btn-primary" data-testid="button-scan-hardware" onClick={() => void onRefresh()}>{refreshing ? <><RefreshCw className="spin" size={14} aria-hidden="true" /> Checking radios</> : <><ScanLine size={14} aria-hidden="true" /> Check this device</>}</button></div>
    {hardwareScan && <div className="scan-result" role="status" aria-live="polite" data-testid="hardware-scan-result">
      <strong>Last check {new Date(hardwareScan.checkedAt).toLocaleTimeString()}.</strong>{' '}
      {hardwareScan.probes} {hardwareScan.probes === 1 ? 'capability' : 'capabilities'} probed in this browser session.{' '}
      {hardwareScan.changes.length
        ? <>Changed since the previous check — {hardwareScan.changes.join('; ')}.</>
        : 'Nothing changed since the previous check, so the cards below are the same answer: this device exposes what it can expose, and no permission prompt is pending.'}
    </div>}
    <div className={`scan-status-banner ${apiStatus}`} role="status"><ShieldCheck aria-hidden="true" /><span><strong>{apiStatus === 'error' ? 'Data service error.' : apiStatus === 'unavailable' ? 'Operator API unavailable.' : apiStatus === 'checking' ? 'Checking connection.' : 'Scan status.'}</strong> {apiStatus === 'error' ? 'The API returned an error while reading devices or relay nodes. Scans cannot be saved until the database connection is repaired.' : apiStatus === 'unavailable' ? 'Cannot connect to the operator API. Check the server and your connection before starting a relay.' : apiStatus === 'checking' ? 'Waiting for the operator API to report its status.' : 'A scan runs only when a local authorized scanner or supported radio action is actively reporting. No sample readings are generated.'}</span></div>
    <div className="signal-banner"><ShieldCheck aria-hidden="true" /><span><strong>{isMobile ? 'Phone-only radio access.' : 'Computer-local radio scan.'}</strong> {isMobile ? 'The phone relay uses position, motion, and — where this browser grants it — a Bluetooth advertisement scan. Camera, microphone, and background activity are never used, and no sensor is opened until you press Start.' : 'Scan here with no install, or use the local bridge for the computer’s WiFi and Bluetooth adapters. Grant any OS permission prompts on that machine.'}</span><span className="hardware-count">{connected}/{supported} usable</span></div>
    <PhoneRelay />
    <div className="stats-grid hardware-stats"><MetricCard label="Usable radios" value={String(connected).padStart(2, '0')} note="Available to this browser" icon={Cpu} /><MetricCard label="Permission gates" value={String(visibleCapabilities.filter(capability => capability.status === 'permission').length).padStart(2, '0')} note="Operator decision required" icon={Shield} /><MetricCard label="RF scan path" value={isMobile ? 'PHONE' : 'LOCAL'} note={isMobile ? 'Browser-exposed phone features only' : 'Computer OS bridge required'} icon={Radio} /><MetricCard label="Relay" value={apiStatus === 'connected' ? 'API OK' : 'BLOCKED'} note={apiStatus === 'connected' ? 'Waiting for scanner heartbeat' : 'Data service not ready'} icon={Smartphone} /></div>
    <div className="panel hardware-panel"><div className="panel-header"><div><div className="panel-title">Detected capability surface</div><div className="panel-subtitle">Results come from this device and this browser session</div></div><div className="status-pill"><span className="pulse-dot" /> DEVICE-AWARE</div></div><div className="capability-grid">{visibleCapabilities.map(capability => <div className={`capability-card ${capability.status}`} key={capability.id} data-testid={`hardware-${capability.id}`}><div className="capability-top"><div className="capability-icon"><CapabilityIcon id={capability.id} /></div><span className={`hardware-status ${capability.status}`}>{statusLabel[capability.status]}</span></div><div className="capability-label">{capability.label}</div><p>{capability.detail}</p><div className="capability-use"><span className="eyebrow">BackSpyne use</span><span>{capability.use}</span></div>{capability.action && <button className="btn capability-action" data-testid={`button-connect-${capability.action}`} onClick={() => void onRequest(capability.id)}>{capability.status === 'connected' ? <><CheckCircle2 size={13} aria-hidden="true" /> Connected</> : <><Plus size={13} aria-hidden="true" /> Choose approved device</>}</button>}</div>)}</div></div>
    {!isMobile && <div className="panel desktop-bridge-guide"><div className="panel-header"><div><div className="panel-title">Start scanning with this computer</div><div className="panel-subtitle">The bridge reads real OS WiFi and Bluetooth adapters</div></div><Cpu size={16} aria-hidden="true" style={{ color: 'hsl(var(--muted-foreground))' }} /></div><div className="bridge-guide-body"><BridgeDownload testId="bridge-download-hardware" /><ol><li>Unzip it on the machine that has the radio adapters.</li><li>Pair a relay on the <a href="/user-portal/relays">Relays</a> page and paste the issued lines into <code>.env</code>; the token is shown once and is never part of the download.</li><li>Run <code>start.ps1</code> on Windows, <code>start.sh</code> on macOS/Linux, or <code>start.bat</code> on Windows Command Prompt.</li><li>Keep the bridge running. The page switches to <strong>Relay active</strong> after a signed heartbeat reaches the server.</li></ol><p>WiFi and BLE scans use OS permissions and adapters on that computer. A browser tab cannot start local programs by itself. If the API/data service is reporting an error above, scans cannot be saved until the server database is repaired.</p></div></div>}
    <div className="panel hardware-note"><div className="panel-header"><div><div className="panel-title">{isMobile ? 'What your phone can scan' : 'What the local bridge can scan'}</div><div className="panel-subtitle">Real device and operating-system limits</div></div><Wifi size={16} aria-hidden="true" style={{ color: 'hsl(var(--muted-foreground))' }} /></div><div className="hardware-note-body"><div><p>{isMobile ? 'A page cannot list nearby WiFi access points: that information is only available to a program running beside the adapter. Bluetooth is different — Chrome on Android exposes an advertisement scan behind its experimental web-platform flag, which reports nearby advertisers by name and level, and reports an identifier this browser keeps for the device rather than its radio address. Where that scan is not exposed, the relay still reports position and movement, which is what places a fixed relay’s measurement in metres.' : 'The local Python scanner uses OS-approved WiFi scan APIs and BLE adapter scans on this computer. It reports access points and visible BLE advertisements only—not every nearby phone or client. CSI requires separately configured compatible hardware. A browser cannot start the scanner process itself.'}</p>{isMobile && <p className="phone-scan-note">Only when you press Start: location for where a measurement was taken, motion for whether the phone was still, and a Bluetooth advertisement scan if this browser exposes one. Camera, microphone, USB, and serial are never requested, and stopping the relay releases every sensor it opened.</p>}</div></div></div>
  </>;
}
