// Hardware: what this machine can actually measure.
//
// The view states the browser's limits instead of asking for permissions on load: a
// capability is probed, reported with the reason it is limited or unsupported, and the
// operating system is only asked for access when the operator presses a button.

import {
  Activity, Bluetooth, CheckCircle2, Cpu, MapPin, Mic, Plus, Radio, RefreshCw, ScanLine,
  Shield, ShieldCheck, Smartphone, Wifi,
} from 'lucide-react';

import { MetricCard } from '../components/console';
import { useConsoleData } from '../lib/console-data';
import type { HardwareCapability, HardwareStatus } from '../lib/types';

function CapabilityIcon({ id }: { id: string }) {
  if (id === 'bluetooth') return <Bluetooth aria-hidden="true" />;
  if (id === 'wifi') return <Wifi aria-hidden="true" />;
  if (id === 'camera-mic') return <Mic aria-hidden="true" />;
  if (id === 'location') return <MapPin aria-hidden="true" />;
  if (id === 'motion') return <Activity aria-hidden="true" />;
  if (id === 'battery') return <Smartphone aria-hidden="true" />;
  return <Cpu aria-hidden="true" />;
}

export function Hardware() {
  const { hardware: capabilities, hardwareRefreshing: refreshing, refreshHardware: onRefresh, requestHardware: onRequest, isMobile, apiStatus } = useConsoleData();
  const visibleCapabilities = isMobile ? capabilities.filter(capability => ['bluetooth', 'wifi'].includes(capability.id)) : capabilities;
  const connected = visibleCapabilities.filter(capability => capability.status === 'connected' || capability.status === 'ready').length;
  const supported = visibleCapabilities.filter(capability => capability.status !== 'unsupported').length;
  const statusLabel: Record<HardwareStatus, string> = { ready: 'ready', permission: 'permission needed', connected: 'connected', limited: 'limited', unsupported: 'not exposed' };
  return <><div className={`page-heading ${isMobile ? 'mobile-scan-heading' : ''}`}><div><div className="page-kicker">{isMobile ? 'Phone radio access' : 'Computer hardware bridge'}</div><h1>{isMobile ? 'Scan with your phone.' : 'Scan with your computer.'}</h1><p>{isMobile ? 'This phone view reports only browser-exposed WiFi link status and optional BLE device selection. Mobile browsers cannot list nearby WiFi networks or passively scan all BLE advertisers.' : 'The browser cannot scan computer radios directly. Run the local BackSpyne bridge on this computer to scan nearby WiFi access points and BLE advertisements with OS-approved adapters.'}</p></div><button className="btn btn-primary" data-testid="button-scan-hardware" onClick={() => void onRefresh()}>{refreshing ? <><RefreshCw className="spin" size={14} aria-hidden="true" /> Checking radios</> : <><ScanLine size={14} aria-hidden="true" /> Check this device</>}</button></div>
    <div className={`scan-status-banner ${apiStatus}`} role="status"><ShieldCheck aria-hidden="true" /><span><strong>{apiStatus === 'error' ? 'Data service error.' : apiStatus === 'unavailable' ? 'Operator API unavailable.' : apiStatus === 'checking' ? 'Checking connection.' : 'Scan status.'}</strong> {apiStatus === 'error' ? 'The API returned an error while reading devices or relay nodes. Scans cannot be saved until the database connection is repaired.' : apiStatus === 'unavailable' ? 'Cannot connect to the operator API. Check the server and your connection before starting a relay.' : apiStatus === 'checking' ? 'Waiting for the operator API to report its status.' : 'A scan runs only when a local authorized scanner or supported radio action is actively reporting. No sample readings are generated.'}</span></div>
    <div className="signal-banner"><ShieldCheck aria-hidden="true" /><span><strong>{isMobile ? 'Phone-only radio access.' : 'Computer-local radio scan.'}</strong> {isMobile ? 'No camera, microphone, location, motion sensor, or background activity is used for RF scanning.' : 'The local bridge uses the computer’s WiFi and Bluetooth hardware. Grant any OS permission prompts on that computer.'}</span><span className="hardware-count">{connected}/{supported} usable</span></div>
    <div className="stats-grid hardware-stats"><MetricCard label="Usable radios" value={String(connected).padStart(2, '0')} note="Available to this browser" icon={Cpu} /><MetricCard label="Permission gates" value={String(visibleCapabilities.filter(capability => capability.status === 'permission').length).padStart(2, '0')} note="Operator decision required" icon={Shield} /><MetricCard label="RF scan path" value={isMobile ? 'PHONE' : 'LOCAL'} note={isMobile ? 'Browser-exposed phone features only' : 'Computer OS bridge required'} icon={Radio} /><MetricCard label="Relay" value={apiStatus === 'connected' ? 'API OK' : 'BLOCKED'} note={apiStatus === 'connected' ? 'Waiting for scanner heartbeat' : 'Data service not ready'} icon={Smartphone} /></div>
    <div className="panel hardware-panel"><div className="panel-header"><div><div className="panel-title">Detected capability surface</div><div className="panel-subtitle">Results come from this device and this browser session</div></div><div className="status-pill"><span className="pulse-dot" /> DEVICE-AWARE</div></div><div className="capability-grid">{visibleCapabilities.map(capability => <div className={`capability-card ${capability.status}`} key={capability.id} data-testid={`hardware-${capability.id}`}><div className="capability-top"><div className="capability-icon"><CapabilityIcon id={capability.id} /></div><span className={`hardware-status ${capability.status}`}>{statusLabel[capability.status]}</span></div><div className="capability-label">{capability.label}</div><p>{capability.detail}</p><div className="capability-use"><span className="eyebrow">BackSpyne use</span><span>{capability.use}</span></div>{capability.action && <button className="btn capability-action" data-testid={`button-connect-${capability.action}`} onClick={() => void onRequest(capability.id)}>{capability.status === 'connected' ? <><CheckCircle2 size={13} aria-hidden="true" /> Connected</> : <><Plus size={13} aria-hidden="true" /> Choose approved device</>}</button>}</div>)}</div></div>
    {!isMobile && <div className="panel desktop-bridge-guide"><div className="panel-header"><div><div className="panel-title">Start scanning with this computer</div><div className="panel-subtitle">The bridge reads real OS WiFi and Bluetooth adapters</div></div><Cpu size={16} aria-hidden="true" style={{ color: 'hsl(var(--muted-foreground))' }} /></div><div className="bridge-guide-body"><ol><li>On the computer, open the BackSpyne project and go to its <strong>scanner</strong> folder.</li><li>Copy <code>.env.example</code> to <code>.env</code>. Set the operator ID and node token to match the server secrets; never share or commit them.</li><li>Run <code>start.ps1</code> on Windows, <code>start.sh</code> on macOS/Linux, or <code>start.bat</code> on Windows Command Prompt.</li><li>Keep the bridge running. The page will switch to <strong>Relay active</strong> after a signed heartbeat reaches the server.</li></ol><p>WiFi and BLE scans use OS permissions and adapters on that computer. A browser tab cannot start local programs by itself. If the API/data service is reporting an error above, scans cannot be saved until the server database is repaired.</p></div></div>}
    <div className="panel hardware-note"><div className="panel-header"><div><div className="panel-title">{isMobile ? 'What your phone can scan' : 'What the local bridge can scan'}</div><div className="panel-subtitle">Real device and operating-system limits</div></div><Wifi size={16} aria-hidden="true" style={{ color: 'hsl(var(--muted-foreground))' }} /></div><div className="hardware-note-body"><div><p>{isMobile ? 'Mobile browsers do not expose nearby WiFi access-point lists. Motion, location, battery, camera, and microphone are not RF scanning. Some Android browsers offer user-selected BLE device connections, but not passive discovery of every advertiser; iOS browsers may not expose Web Bluetooth. A dedicated native app or local scanner hardware is needed for broader scans.' : 'The local Python scanner uses OS-approved WiFi scan APIs and BLE adapter scans on this computer. It reports access points and visible BLE advertisements only—not every nearby phone or client. CSI requires separately configured compatible hardware. A browser cannot start the scanner process itself.'}</p>{isMobile && <p className="phone-scan-note">This phone view intentionally offers only WiFi status and browser-exposed Bluetooth access. It does not request camera, microphone, location, motion, USB, or serial permissions.</p>}</div></div></div>
  </>;
}
